# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 910)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setup_frame = QtWidgets.QFrame(self.centralwidget)
        self.setup_frame.setGeometry(QtCore.QRect(10, 10, 1080, 500))
        self.setup_frame.setStyleSheet("")
        self.setup_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.setup_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.setup_frame.setObjectName("setup_frame")
        self.rightImage_graphicsView = ImageView(self.setup_frame)
        self.rightImage_graphicsView.setGeometry(QtCore.QRect(800, 210, 256, 192))
        self.rightImage_graphicsView.setObjectName("rightImage_graphicsView")
        self.bottomImage_graphicsView = ImageView(self.setup_frame)
        self.bottomImage_graphicsView.setGeometry(QtCore.QRect(540, 210, 256, 192))
        self.bottomImage_graphicsView.setObjectName("bottomImage_graphicsView")
        self.leftImage_graphicsView = ImageView(self.setup_frame)
        self.leftImage_graphicsView.setGeometry(QtCore.QRect(280, 210, 256, 192))
        self.leftImage_graphicsView.setObjectName("leftImage_graphicsView")
        self.topImage_graphicsView = ImageView(self.setup_frame)
        self.topImage_graphicsView.setGeometry(QtCore.QRect(20, 210, 256, 192))
        self.topImage_graphicsView.setObjectName("topImage_graphicsView")
        self.topImage_label = QtWidgets.QLabel(self.setup_frame)
        self.topImage_label.setGeometry(QtCore.QRect(120, 170, 41, 31))
        self.topImage_label.setStyleSheet("")
        self.topImage_label.setObjectName("topImage_label")
        self.leftImage_label = QtWidgets.QLabel(self.setup_frame)
        self.leftImage_label.setGeometry(QtCore.QRect(400, 170, 41, 31))
        self.leftImage_label.setObjectName("leftImage_label")
        self.selectedSlide_label = QtWidgets.QLabel(self.setup_frame)
        self.selectedSlide_label.setGeometry(QtCore.QRect(250, 10, 151, 31))
        self.selectedSlide_label.setObjectName("selectedSlide_label")
        self.selectedSlide_graphicsView = ImageView(self.setup_frame)
        self.selectedSlide_graphicsView.setGeometry(QtCore.QRect(170, 50, 291, 91))
        self.selectedSlide_graphicsView.setObjectName("selectedSlide_graphicsView")
        self.bottomImage_label = QtWidgets.QLabel(self.setup_frame)
        self.bottomImage_label.setGeometry(QtCore.QRect(630, 170, 71, 31))
        self.bottomImage_label.setObjectName("bottomImage_label")
        self.rightImage_label = QtWidgets.QLabel(self.setup_frame)
        self.rightImage_label.setGeometry(QtCore.QRect(910, 170, 51, 31))
        self.rightImage_label.setObjectName("rightImage_label")
        self.snapTop_pushButton = QtWidgets.QPushButton(self.setup_frame)
        self.snapTop_pushButton.setGeometry(QtCore.QRect(100, 410, 75, 23))
        self.snapTop_pushButton.setObjectName("snapTop_pushButton")
        self.snapLeft_pushButton = QtWidgets.QPushButton(self.setup_frame)
        self.snapLeft_pushButton.setGeometry(QtCore.QRect(370, 410, 75, 23))
        self.snapLeft_pushButton.setObjectName("snapLeft_pushButton")
        self.snapBottom_pushButton = QtWidgets.QPushButton(self.setup_frame)
        self.snapBottom_pushButton.setGeometry(QtCore.QRect(630, 410, 75, 23))
        self.snapBottom_pushButton.setObjectName("snapBottom_pushButton")
        self.snapRight_pushButton = QtWidgets.QPushButton(self.setup_frame)
        self.snapRight_pushButton.setGeometry(QtCore.QRect(890, 410, 75, 23))
        self.snapRight_pushButton.setObjectName("snapRight_pushButton")
        self.topWell_spinBox = QtWidgets.QSpinBox(self.setup_frame)
        self.topWell_spinBox.setGeometry(QtCore.QRect(210, 410, 42, 22))
        self.topWell_spinBox.setMinimum(1)
        self.topWell_spinBox.setMaximum(8)
        self.topWell_spinBox.setObjectName("topWell_spinBox")
        self.leftWell_spinBox = QtWidgets.QSpinBox(self.setup_frame)
        self.leftWell_spinBox.setGeometry(QtCore.QRect(480, 410, 42, 22))
        self.leftWell_spinBox.setMinimum(1)
        self.leftWell_spinBox.setMaximum(8)
        self.leftWell_spinBox.setObjectName("leftWell_spinBox")
        self.bottomWell_spinBox = QtWidgets.QSpinBox(self.setup_frame)
        self.bottomWell_spinBox.setGeometry(QtCore.QRect(740, 410, 42, 22))
        self.bottomWell_spinBox.setMinimum(1)
        self.bottomWell_spinBox.setMaximum(8)
        self.bottomWell_spinBox.setObjectName("bottomWell_spinBox")
        self.rightWell_spinBox = QtWidgets.QSpinBox(self.setup_frame)
        self.rightWell_spinBox.setGeometry(QtCore.QRect(1000, 410, 42, 22))
        self.rightWell_spinBox.setMinimum(1)
        self.rightWell_spinBox.setMaximum(8)
        self.rightWell_spinBox.setObjectName("rightWell_spinBox")
        self.wellTop_label = QtWidgets.QLabel(self.setup_frame)
        self.wellTop_label.setGeometry(QtCore.QRect(180, 410, 31, 21))
        self.wellTop_label.setObjectName("wellTop_label")
        self.wellLeft_label = QtWidgets.QLabel(self.setup_frame)
        self.wellLeft_label.setGeometry(QtCore.QRect(450, 410, 31, 21))
        self.wellLeft_label.setObjectName("wellLeft_label")
        self.wellBottom_label = QtWidgets.QLabel(self.setup_frame)
        self.wellBottom_label.setGeometry(QtCore.QRect(710, 410, 31, 21))
        self.wellBottom_label.setObjectName("wellBottom_label")
        self.wellRight_label = QtWidgets.QLabel(self.setup_frame)
        self.wellRight_label.setGeometry(QtCore.QRect(970, 410, 31, 21))
        self.wellRight_label.setObjectName("wellRight_label")
        self.calcRotation_label = QtWidgets.QLabel(self.setup_frame)
        self.calcRotation_label.setGeometry(QtCore.QRect(590, 20, 141, 21))
        self.calcRotation_label.setObjectName("calcRotation_label")
        self.calcTip_label = QtWidgets.QLabel(self.setup_frame)
        self.calcTip_label.setGeometry(QtCore.QRect(750, 20, 111, 21))
        self.calcTip_label.setObjectName("calcTip_label")
        self.calcTip_label_2 = QtWidgets.QLabel(self.setup_frame)
        self.calcTip_label_2.setGeometry(QtCore.QRect(890, 20, 111, 21))
        self.calcTip_label_2.setObjectName("calcTip_label_2")
        self.rotation_graphicsView = QtWidgets.QGraphicsView(self.setup_frame)
        self.rotation_graphicsView.setGeometry(QtCore.QRect(610, 40, 100, 100))
        self.rotation_graphicsView.setStyleSheet("background-image: url(:/calcRotation/RotationSmall.png);")
        self.rotation_graphicsView.setObjectName("rotation_graphicsView")
        self.tip_graphicsView = QtWidgets.QGraphicsView(self.setup_frame)
        self.tip_graphicsView.setGeometry(QtCore.QRect(750, 40, 100, 100))
        self.tip_graphicsView.setStyleSheet("background-image: url(:/calcTip/TipSmall.png);")
        self.tip_graphicsView.setObjectName("tip_graphicsView")
        self.graphicsView = QtWidgets.QGraphicsView(self.setup_frame)
        self.graphicsView.setGeometry(QtCore.QRect(890, 40, 100, 100))
        self.graphicsView.setStyleSheet("background-image: url(:/calcTilt/TiltSmall.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.calcRot_label = QtWidgets.QLabel(self.setup_frame)
        self.calcRot_label.setGeometry(QtCore.QRect(630, 140, 61, 16))
        self.calcRot_label.setObjectName("calcRot_label")
        self.calcTip_label_3 = QtWidgets.QLabel(self.setup_frame)
        self.calcTip_label_3.setGeometry(QtCore.QRect(770, 140, 61, 16))
        self.calcTip_label_3.setObjectName("calcTip_label_3")
        self.calcTilt_label = QtWidgets.QLabel(self.setup_frame)
        self.calcTilt_label.setGeometry(QtCore.QRect(910, 140, 61, 16))
        self.calcTilt_label.setObjectName("calcTilt_label")
        self.runCalc_pushButton = QtWidgets.QPushButton(self.setup_frame)
        self.runCalc_pushButton.setGeometry(QtCore.QRect(500, 450, 91, 41))
        self.runCalc_pushButton.setObjectName("runCalc_pushButton")
        self.expt_frame = QtWidgets.QFrame(self.centralwidget)
        self.expt_frame.setGeometry(QtCore.QRect(10, 520, 1081, 331))
        self.expt_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.expt_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.expt_frame.setObjectName("expt_frame")
        self.acquisition_frame = QtWidgets.QFrame(self.expt_frame)
        self.acquisition_frame.setGeometry(QtCore.QRect(300, 10, 270, 310))
        self.acquisition_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.acquisition_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.acquisition_frame.setObjectName("acquisition_frame")
        self.centerWells_radioButton = QtWidgets.QRadioButton(self.acquisition_frame)
        self.centerWells_radioButton.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.centerWells_radioButton.setObjectName("centerWells_radioButton")
        self.randomROIs_radioButton = QtWidgets.QRadioButton(self.acquisition_frame)
        self.randomROIs_radioButton.setGeometry(QtCore.QRect(140, 60, 91, 17))
        self.randomROIs_radioButton.setObjectName("randomROIs_radioButton")
        self.nROIs_spinBox = QtWidgets.QSpinBox(self.acquisition_frame)
        self.nROIs_spinBox.setGeometry(QtCore.QRect(180, 100, 42, 22))
        self.nROIs_spinBox.setObjectName("nROIs_spinBox")
        self.rows_spinBox = QtWidgets.QSpinBox(self.acquisition_frame)
        self.rows_spinBox.setGeometry(QtCore.QRect(30, 100, 42, 22))
        self.rows_spinBox.setObjectName("rows_spinBox")
        self.columns_spinBox = QtWidgets.QSpinBox(self.acquisition_frame)
        self.columns_spinBox.setGeometry(QtCore.QRect(90, 100, 42, 22))
        self.columns_spinBox.setObjectName("columns_spinBox")
        self.nROIs_label = QtWidgets.QLabel(self.acquisition_frame)
        self.nROIs_label.setGeometry(QtCore.QRect(180, 80, 41, 21))
        self.nROIs_label.setObjectName("nROIs_label")
        self.nRows_label = QtWidgets.QLabel(self.acquisition_frame)
        self.nRows_label.setGeometry(QtCore.QRect(30, 80, 47, 21))
        self.nRows_label.setObjectName("nRows_label")
        self.nColumns_label = QtWidgets.QLabel(self.acquisition_frame)
        self.nColumns_label.setGeometry(QtCore.QRect(90, 80, 51, 21))
        self.nColumns_label.setObjectName("nColumns_label")
        self.volumeTop_lineEdit = QtWidgets.QLineEdit(self.acquisition_frame)
        self.volumeTop_lineEdit.setGeometry(QtCore.QRect(40, 200, 81, 20))
        self.volumeTop_lineEdit.setObjectName("volumeTop_lineEdit")
        self.volumeBottom_lineEdit = QtWidgets.QLineEdit(self.acquisition_frame)
        self.volumeBottom_lineEdit.setGeometry(QtCore.QRect(40, 230, 81, 20))
        self.volumeBottom_lineEdit.setObjectName("volumeBottom_lineEdit")
        self.umTop_label = QtWidgets.QLabel(self.acquisition_frame)
        self.umTop_label.setGeometry(QtCore.QRect(120, 200, 91, 20))
        self.umTop_label.setObjectName("umTop_label")
        self.umBottom_label = QtWidgets.QLabel(self.acquisition_frame)
        self.umBottom_label.setGeometry(QtCore.QRect(120, 230, 101, 16))
        self.umBottom_label.setObjectName("umBottom_label")
        self.stepSize_lineEdit = QtWidgets.QLineEdit(self.acquisition_frame)
        self.stepSize_lineEdit.setGeometry(QtCore.QRect(40, 260, 81, 20))
        self.stepSize_lineEdit.setObjectName("stepSize_lineEdit")
        self.stepSize_label = QtWidgets.QLabel(self.acquisition_frame)
        self.stepSize_label.setGeometry(QtCore.QRect(120, 260, 71, 16))
        self.stepSize_label.setObjectName("stepSize_label")
        self.grid_label = QtWidgets.QLabel(self.acquisition_frame)
        self.grid_label.setGeometry(QtCore.QRect(80, 20, 111, 31))
        self.grid_label.setObjectName("grid_label")
        self.volume_label = QtWidgets.QLabel(self.acquisition_frame)
        self.volume_label.setGeometry(QtCore.QRect(60, 140, 141, 31))
        self.volume_label.setObjectName("volume_label")
        self.zeroUm_label = QtWidgets.QLabel(self.acquisition_frame)
        self.zeroUm_label.setGeometry(QtCore.QRect(60, 170, 131, 16))
        self.zeroUm_label.setObjectName("zeroUm_label")
        self.selectWells_frame = QtWidgets.QFrame(self.expt_frame)
        self.selectWells_frame.setGeometry(QtCore.QRect(20, 10, 270, 310))
        self.selectWells_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.selectWells_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selectWells_frame.setObjectName("selectWells_frame")
        self.selectWells_label = QtWidgets.QLabel(self.selectWells_frame)
        self.selectWells_label.setGeometry(QtCore.QRect(80, 20, 111, 31))
        self.selectWells_label.setObjectName("selectWells_label")
        self.well1_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well1_checkBox.setGeometry(QtCore.QRect(30, 50, 51, 21))
        self.well1_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well1_checkBox.setCheckable(True)
        self.well1_checkBox.setObjectName("well1_checkBox")
        self.well2_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well2_checkBox.setGeometry(QtCore.QRect(80, 50, 51, 21))
        self.well2_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well2_checkBox.setCheckable(True)
        self.well2_checkBox.setObjectName("well2_checkBox")
        self.well3_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well3_checkBox.setGeometry(QtCore.QRect(130, 50, 51, 21))
        self.well3_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well3_checkBox.setCheckable(True)
        self.well3_checkBox.setObjectName("well3_checkBox")
        self.well4_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well4_checkBox.setGeometry(QtCore.QRect(180, 50, 51, 21))
        self.well4_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well4_checkBox.setCheckable(True)
        self.well4_checkBox.setObjectName("well4_checkBox")
        self.well5_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well5_checkBox.setGeometry(QtCore.QRect(30, 70, 51, 21))
        self.well5_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well5_checkBox.setCheckable(True)
        self.well5_checkBox.setObjectName("well5_checkBox")
        self.well6_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well6_checkBox.setGeometry(QtCore.QRect(80, 70, 51, 21))
        self.well6_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well6_checkBox.setCheckable(True)
        self.well6_checkBox.setObjectName("well6_checkBox")
        self.well7_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well7_checkBox.setGeometry(QtCore.QRect(130, 70, 51, 21))
        self.well7_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well7_checkBox.setCheckable(True)
        self.well7_checkBox.setObjectName("well7_checkBox")
        self.well8_checkBox = QtWidgets.QCheckBox(self.selectWells_frame)
        self.well8_checkBox.setGeometry(QtCore.QRect(180, 70, 51, 21))
        self.well8_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.well8_checkBox.setCheckable(True)
        self.well8_checkBox.setObjectName("well8_checkBox")
        self.frame = QtWidgets.QFrame(self.expt_frame)
        self.frame.setGeometry(QtCore.QRect(580, 10, 270, 310))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.timelapse_label = QtWidgets.QLabel(self.frame)
        self.timelapse_label.setGeometry(QtCore.QRect(90, 20, 101, 31))
        self.timelapse_label.setObjectName("timelapse_label")
        self.timelapse_checkBox = QtWidgets.QCheckBox(self.frame)
        self.timelapse_checkBox.setGeometry(QtCore.QRect(100, 60, 81, 21))
        self.timelapse_checkBox.setObjectName("timelapse_checkBox")
        self.timePoints_spinBox = QtWidgets.QSpinBox(self.frame)
        self.timePoints_spinBox.setGeometry(QtCore.QRect(130, 90, 42, 22))
        self.timePoints_spinBox.setObjectName("timePoints_spinBox")
        self.nTimepoints_label = QtWidgets.QLabel(self.frame)
        self.nTimepoints_label.setGeometry(QtCore.QRect(20, 90, 111, 20))
        self.nTimepoints_label.setObjectName("nTimepoints_label")
        self.interval_spinBox = QtWidgets.QSpinBox(self.frame)
        self.interval_spinBox.setGeometry(QtCore.QRect(130, 110, 42, 22))
        self.interval_spinBox.setObjectName("interval_spinBox")
        self.interval_label = QtWidgets.QLabel(self.frame)
        self.interval_label.setGeometry(QtCore.QRect(90, 110, 41, 20))
        self.interval_label.setObjectName("interval_label")
        self.units_comboBox = QtWidgets.QComboBox(self.frame)
        self.units_comboBox.setGeometry(QtCore.QRect(180, 110, 69, 22))
        self.units_comboBox.setMaxVisibleItems(3)
        self.units_comboBox.setObjectName("units_comboBox")
        self.units_comboBox.addItem("")
        self.units_comboBox.addItem("")
        self.units_comboBox.addItem("")
        self.channels_label = QtWidgets.QLabel(self.frame)
        self.channels_label.setGeometry(QtCore.QRect(90, 140, 91, 31))
        self.channels_label.setObjectName("channels_label")
        self.ch1_checkBox = QtWidgets.QCheckBox(self.frame)
        self.ch1_checkBox.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.ch1_checkBox.setObjectName("ch1_checkBox")
        self.ch2_checkBox = QtWidgets.QCheckBox(self.frame)
        self.ch2_checkBox.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.ch2_checkBox.setObjectName("ch2_checkBox")
        self.ch3_checkBox = QtWidgets.QCheckBox(self.frame)
        self.ch3_checkBox.setGeometry(QtCore.QRect(20, 220, 70, 17))
        self.ch3_checkBox.setObjectName("ch3_checkBox")
        self.ch4_checkBox = QtWidgets.QCheckBox(self.frame)
        self.ch4_checkBox.setGeometry(QtCore.QRect(20, 240, 70, 17))
        self.ch4_checkBox.setObjectName("ch4_checkBox")
        self.ch5_checkBox = QtWidgets.QCheckBox(self.frame)
        self.ch5_checkBox.setGeometry(QtCore.QRect(20, 260, 70, 17))
        self.ch5_checkBox.setObjectName("ch5_checkBox")
        self.ch6_checkBox = QtWidgets.QCheckBox(self.frame)
        self.ch6_checkBox.setGeometry(QtCore.QRect(20, 280, 70, 17))
        self.ch6_checkBox.setObjectName("ch6_checkBox")
        self.ch1Ex_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ch1Ex_lineEdit.setGeometry(QtCore.QRect(90, 180, 113, 20))
        self.ch1Ex_lineEdit.setObjectName("ch1Ex_lineEdit")
        self.ch2Ex_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ch2Ex_lineEdit.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.ch2Ex_lineEdit.setObjectName("ch2Ex_lineEdit")
        self.ch3Ex_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ch3Ex_lineEdit.setGeometry(QtCore.QRect(90, 220, 113, 20))
        self.ch3Ex_lineEdit.setObjectName("ch3Ex_lineEdit")
        self.ch4Ex_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ch4Ex_lineEdit.setGeometry(QtCore.QRect(90, 240, 113, 20))
        self.ch4Ex_lineEdit.setObjectName("ch4Ex_lineEdit")
        self.ch5Ex_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ch5Ex_lineEdit.setGeometry(QtCore.QRect(90, 260, 113, 20))
        self.ch5Ex_lineEdit.setObjectName("ch5Ex_lineEdit")
        self.ch6Ex_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ch6Ex_lineEdit.setGeometry(QtCore.QRect(90, 280, 113, 20))
        self.ch6Ex_lineEdit.setObjectName("ch6Ex_lineEdit")
        self.ch1ms_label = QtWidgets.QLabel(self.frame)
        self.ch1ms_label.setGeometry(QtCore.QRect(210, 180, 21, 21))
        self.ch1ms_label.setObjectName("ch1ms_label")
        self.ch2ms_label = QtWidgets.QLabel(self.frame)
        self.ch2ms_label.setGeometry(QtCore.QRect(210, 200, 21, 21))
        self.ch2ms_label.setObjectName("ch2ms_label")
        self.ch3ms_label = QtWidgets.QLabel(self.frame)
        self.ch3ms_label.setGeometry(QtCore.QRect(210, 220, 21, 21))
        self.ch3ms_label.setObjectName("ch3ms_label")
        self.ch4ms_label = QtWidgets.QLabel(self.frame)
        self.ch4ms_label.setGeometry(QtCore.QRect(210, 240, 21, 21))
        self.ch4ms_label.setObjectName("ch4ms_label")
        self.ch5ms_label = QtWidgets.QLabel(self.frame)
        self.ch5ms_label.setGeometry(QtCore.QRect(210, 260, 21, 21))
        self.ch5ms_label.setObjectName("ch5ms_label")
        self.ch6ms_label = QtWidgets.QLabel(self.frame)
        self.ch6ms_label.setGeometry(QtCore.QRect(210, 280, 21, 21))
        self.ch6ms_label.setObjectName("ch6ms_label")
        self.MM_pushButton = QtWidgets.QPushButton(self.expt_frame)
        self.MM_pushButton.setGeometry(QtCore.QRect(900, 100, 141, 101))
        self.MM_pushButton.setStyleSheet("")
        self.MM_pushButton.setObjectName("MM_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        self.menuSlide = QtWidgets.QMenu(self.menubar)
        self.menuSlide.setObjectName("menuSlide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIbidi_8_Well = QtWidgets.QAction(MainWindow)
        self.actionIbidi_8_Well.setObjectName("actionIbidi_8_Well")
        self.menuSlide.addAction(self.actionIbidi_8_Well)
        self.menubar.addAction(self.menuSlide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topImage_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ff0000;\">Top</span></p></body></html>"))
        self.leftImage_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#00ff00;\">Left</span></p></body></html>"))
        self.selectedSlide_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Selected Slide</span></p></body></html>"))
        self.bottomImage_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#0000ff;\">Bottom</span></p></body></html>"))
        self.rightImage_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffff00;\">Right</span></p></body></html>"))
        self.snapTop_pushButton.setText(_translate("MainWindow", "Snap Image"))
        self.snapLeft_pushButton.setText(_translate("MainWindow", "Snap Image"))
        self.snapBottom_pushButton.setText(_translate("MainWindow", "Snap Image"))
        self.snapRight_pushButton.setText(_translate("MainWindow", "Snap Image"))
        self.wellTop_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Well</span></p></body></html>"))
        self.wellLeft_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Well</span></p></body></html>"))
        self.wellBottom_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Well</span></p></body></html>"))
        self.wellRight_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Well</span></p></body></html>"))
        self.calcRotation_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Calculated Rotation</span></p></body></html>"))
        self.calcTip_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Calculated Tip</span></p></body></html>"))
        self.calcTip_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Calculated Tilt</span></p></body></html>"))
        self.calcRot_label.setText(_translate("MainWindow", "XX Degrees"))
        self.calcTip_label_3.setText(_translate("MainWindow", "XX Degrees"))
        self.calcTilt_label.setText(_translate("MainWindow", "XX Degrees"))
        self.runCalc_pushButton.setText(_translate("MainWindow", "Run Calculation"))
        self.centerWells_radioButton.setText(_translate("MainWindow", "Center of Wells"))
        self.randomROIs_radioButton.setText(_translate("MainWindow", "Random ROIs"))
        self.nROIs_label.setText(_translate("MainWindow", "# ROIs"))
        self.nRows_label.setText(_translate("MainWindow", "# Rows"))
        self.nColumns_label.setText(_translate("MainWindow", "# Columns"))
        self.umTop_label.setText(_translate("MainWindow", "um  Top of Volume"))
        self.umBottom_label.setText(_translate("MainWindow", "um Bottom of Volume"))
        self.stepSize_label.setText(_translate("MainWindow", "um Step Size"))
        self.grid_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Grid Setup</span></p></body></html>"))
        self.volume_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Volume Setup</span></p></body></html>"))
        self.zeroUm_label.setText(_translate("MainWindow", "(0 um is Coverslip Surface)"))
        self.selectWells_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Select Wells</span></p></body></html>"))
        self.well1_checkBox.setText(_translate("MainWindow", "Well 1"))
        self.well2_checkBox.setText(_translate("MainWindow", "Well 2"))
        self.well3_checkBox.setText(_translate("MainWindow", "Well 3"))
        self.well4_checkBox.setText(_translate("MainWindow", "Well 4"))
        self.well5_checkBox.setText(_translate("MainWindow", "Well 5"))
        self.well6_checkBox.setText(_translate("MainWindow", "Well 6"))
        self.well7_checkBox.setText(_translate("MainWindow", "Well 7"))
        self.well8_checkBox.setText(_translate("MainWindow", "Well 8"))
        self.timelapse_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Timelapse Setup</span></p></body></html>"))
        self.timelapse_checkBox.setText(_translate("MainWindow", "Do Timelapse"))
        self.nTimepoints_label.setText(_translate("MainWindow", "Number of Time Points"))
        self.interval_label.setText(_translate("MainWindow", "Interval"))
        self.units_comboBox.setItemText(0, _translate("MainWindow", "ms"))
        self.units_comboBox.setItemText(1, _translate("MainWindow", "s"))
        self.units_comboBox.setItemText(2, _translate("MainWindow", "min"))
        self.channels_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Channels</span></p></body></html>"))
        self.ch1_checkBox.setText(_translate("MainWindow", "ch1"))
        self.ch2_checkBox.setText(_translate("MainWindow", "ch2"))
        self.ch3_checkBox.setText(_translate("MainWindow", "ch3"))
        self.ch4_checkBox.setText(_translate("MainWindow", "ch4"))
        self.ch5_checkBox.setText(_translate("MainWindow", "ch5"))
        self.ch6_checkBox.setText(_translate("MainWindow", "ch6"))
        self.ch1ms_label.setText(_translate("MainWindow", "ms"))
        self.ch2ms_label.setText(_translate("MainWindow", "ms"))
        self.ch3ms_label.setText(_translate("MainWindow", "ms"))
        self.ch4ms_label.setText(_translate("MainWindow", "ms"))
        self.ch5ms_label.setText(_translate("MainWindow", "ms"))
        self.ch6ms_label.setText(_translate("MainWindow", "ms"))
        self.MM_pushButton.setText(_translate("MainWindow", "Push To MicroMagellan"))
        self.menuSlide.setTitle(_translate("MainWindow", "Slide"))
        self.actionIbidi_8_Well.setText(_translate("MainWindow", "Ibidi 8 Well"))

from pyqtgraph import ImageView
import GUI_Images_rc
